- first: Mark 
  last: Pallen
  title: Professor
- first: Phil 
  last: Hugenholtz
  title: Professor
- first: Iain
  last: Sutcliffe
  title: Professor
- first: Henk
  last: Den Bakker
  title: Professor
- first: Leighton
  last: Pritchard
  title: Dr.
- first: Conor
  last: Meehan
  title: Dr.

